theme: minima
title: RunAsh
author: Ram Murmu 
email: admin@runash.in
description: > # this means to ignore newlines until "baseurl:"
Write an awesome description for your new site here.you can edit this line in _coonfig.yml.it will appear in your documents head meta (for search results) and in your feed .xml site description

# Social links
twitter_username: -rammurmu # DO NOT include the @ character, or else the build will fail!
linkedin_username: RamMurmu
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage















